server:
  port: 9005
spring:
  application:
    name: study-board-article-read-service
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: study-board-article-read-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
endpoints:
  study-board-article-service:
    url: http://127.0.0.1:9000
  study-board-comment-service:
    url: http://127.0.0.1:9001
  study-board-like-service:
    url: http://127.0.0.1:9002
  study-board-view-service:
    url: http://127.0.0.1:9003
